Homework #2 done
AegisVP/goit-node-REST-API-HW pull request #1
Opened 2022-10-30 01:41 UTC by AegisVP

Homework is finished

2022-10-30 07:42 UTC, Eastvarga commented on node/constants.js
> +const CONST = {
Не вірне найменування файлу - це конфігураційні данні проекту - не просто сталі.
Тому краще використовувати відповідне  config замість CONST

2022-10-30 07:48 UTC, Eastvarga commented on node/contactAPI.js
> +  const contacts = db.readData();
Користуйтеся деструктивним присвоєнням для іьпортів const {readData,writeData} = require('./handleFile.js');
В контексті цього завдання так буде краще читатись код

2022-10-30 07:52 UTC, AegisVP commented on node/constants.js
> +const CONST = {
прийняв, виправив

2022-10-30 07:53 UTC, AegisVP commented on node/constants.js
> +const CONST = {
прийняв, виправив

2022-10-30 07:55 UTC, Eastvarga commented on node/contactAPI.js
> +  if (contacts.length === newContactsList.length) return 404;
Некоректна логіка - не можна яка результат видалення елементу повертати статус процесу - функція  deleteContact(id) нічого не повинна знати о процесі, вона приймає айді елемента та відповідно до логіки видаляє його та повертає результат або помилку (сам об'єкт чи повідомлення з результатом або помилкою) А вже на основі подальшої логіки статус запросу встановлюється.

2022-10-30 08:02 UTC, Eastvarga commented on node/contactAPI.js
> +  return true;
Теж не зрозуміла логіка. Чому на додавання контакту ми завжди отримаємо true, а коли це буде fakse?
Коректно буде повертати як результат сам контакт або помилку запису. Зазвичай функії котрі повертають буль іменуються відповідно логіці isContactAdded()  isNameValid() та повертають одне з двох значень буля

2022-10-30 08:05 UTC, AegisVP commented on node/contactAPI.js
> +  const contacts = db.readData();
Добре, виправив

2022-10-30 08:06 UTC, Eastvarga commented on node/contactAPI.js
> +  if (savedContactData === null) return 404;
теж саме, getContactById(id) повертати має сам об'єкт або undefined  не null. null - це буквально значення. До тогож в js це об'єкт, а Вам потрібно використовуваци в цьому випадку undefined. Та знову повертання коду статусу, не повинно цього бути

2022-10-30 08:16 UTC, Eastvarga commented on node/contactAPI.js
> +  addContact(newContact);
Ніколи так не робіть. Для апдейту контакту не можна використовувати видалення а потім створення нового об'єкта з тим же ID. Все це вирішуеться простим map() по массіву контактів, або локальною заміною оновленного елемента в массиві усіх елементів, а потім вже запис у файл.

2022-10-30 08:17 UTC, Eastvarga commented on node/handleFile.js
> +  return JSON.parse(fs.readFileSync(filePath, CONST.fileEncoding));
використовуйте асінхронні функції, чи Ви їх не розумієте?
Відсутня обробка помилок - я кщо файл буде відсутній, як поведе себе ваш код?

2022-10-30 08:20 UTC, Eastvarga commented on node/contactAPI.js
> +  db.writeData(CONST.defaultPath, contacts);
за зомовченням у Вас вже є  заданий шлях, чому ви його тут використовуєте тоді? Навіщо для функції добавляли його тоді?

2022-10-30 08:24 UTC, Eastvarga commented on node/handleFile.js
> +const writeData = (filePath = CONST.defaultPath, fileContents = '') => {
writeData = (fileContents,  filePath = CONST.defaultPath )
 Ось так коректно використовувати параметри з дефолтним значенням у  функціях, тоді у Вас не виникне проблем з тим, що ви будете використовувати  db.writeData(contacts);   замість   db.writeData(CONST.defaultPath, contacts);

2022-10-30 08:25 UTC, Eastvarga commented on node/index.js
> +const { log } = require('./log.js');
зайве, можна було і не додавати це в проект

2022-10-30 08:26 UTC, Eastvarga commented on node/node.js
> +app.get('/api/contacts', (req, res) => {
роутер не використано. Користуйтесь роутером не треба все робити в файлі ініціалізації сервера

2022-10-30 08:31 UTC, Eastvarga commented on node/node.js
> +    if (result === 404) {
тут має бути не статус код, а, наприклад if (!result)

2022-10-30 08:37 UTC, Eastvarga requested changes
Дуже багато помилок, що до логіки, та розуміння матеріалу.
Треба усунути зауваженя,
Прошу усунути помилки, ще раз прочитати теорію, подиватись заняття за темою, та поспілкуватись з товаришами.
Складається враження, що ви не зовсім розумієте що робите, точніше, як працює код.
Якщо вам щось не зрозуміло, обов'язково спілкуйтеся та запитуйте, на сам перед зі своїми товаришами, не бійтеся бо це Ваш і тільки Ваш розвиток.

2022-11-02 03:16 UTC, AegisVP commented on node/contactAPI.js
> +  if (contacts.length === newContactsList.length) return 404;
Переробив

2022-11-02 03:16 UTC, AegisVP commented on node/contactAPI.js
> +  return true;
теж переробив і додав обробку помилок

2022-11-02 03:17 UTC, AegisVP commented on node/contactAPI.js
> +  if (savedContactData === null) return 404;
переробив. повертаю об'єкт зі статусом і данними

2022-11-02 03:17 UTC, AegisVP commented on node/contactAPI.js
> +  addContact(newContact);
переробив

2022-11-02 03:19 UTC, AegisVP commented on node/handleFile.js
> +  return JSON.parse(fs.readFileSync(filePath, CONST.fileEncoding));
рефакторнув на асинхронні функції. Ще не зовсім їх розумію (зовсім новий концепт для мене) і не завжди вмію швидко написати код з асинхронними функціями

2022-11-02 03:19 UTC, AegisVP commented on node/contactAPI.js
> +  db.writeData(CONST.defaultPath, contacts);
переробив

2022-11-02 03:19 UTC, AegisVP commented on node/handleFile.js
> +const writeData = (filePath = CONST.defaultPath, fileContents = '') => {
згоден. переробив

2022-11-02 03:20 UTC, AegisVP commented on node/index.js
> +const { log } = require('./log.js');
то було для тестів для мене (щоб замість console.log(...) скоротити написання на log(...)) і забув видалити

2022-11-02 03:21 UTC, AegisVP commented on node/node.js
> +app.get('/api/contacts', (req, res) => {
додав роутер. коли писав, я ще не пройшов цю частину навчання :(

2022-11-02 03:21 UTC, AegisVP commented on node/node.js
> +    if (result === 404) {
змінив: повертаю об'єкт із статусом і данними

2022-11-02 03:52 UTC, AegisVP commented
Так. Я коли писав другу домашку, ще не встиг пройти конспект та продивитись відео. 
Зараз пройшов теорію та відео, переробив більшість коду, додав перевірку Joi (з власною обробкою і поверненням відповідей). 
Додав ще функціонал PATCH де можна оновлювати окремо поля а не цілком весь об'єкт.
Левову частину перевірок залишив в роутері а не в API щоб не перекидати ще більше данних між функціями...

2022-11-02 12:20 UTC, Eastvarga commented on node/config.js
> +const CONF = {
просто config бо CONF не зрозуміло, та і об'єкт не є сталою тому капсом ім'я не повинно бути

2022-11-02 12:24 UTC, Eastvarga commented on node/contactAPI.js
> +    return success(res.data);
не вірне іменування - generateSuccessData точніше відповідає суті функції яку ви використовуєте

2022-11-02 12:24 UTC, Eastvarga commented on node/contactAPI.js
> +    return failure([]);
теж саме

2022-11-02 12:30 UTC, Eastvarga commented on node/contactAPI.js
> +  if (contacts.length <= 0) await listContacts();
Полюбляєте обтяжувати собі життя =) імітуєте кешування данних, але в поточному завданні ви просто створили зайву змінну, котра жре пам'ять. Це не критично, та інколи так робити не варто.

2022-11-02 12:35 UTC, AegisVP commented on node/config.js
> +const CONF = {
переробив на dotenv, видалив файл

2022-11-02 12:35 UTC, Eastvarga commented on node/routes/contactsRouter.js
> +router.patch('/:id', async (req, res) => {
Не має бути два ендпоінти з однією логікою - для апдейта елементу лише PUT по завданню. Будьте уважні

2022-11-02 12:38 UTC, Eastvarga approved these changes
Добре, але декілька коментів я залишив

2022-11-02 12:38 UTC, merged

2022-11-02 12:39 UTC, AegisVP commented on node/contactAPI.js
> +    return success(res.data);
Добре, переробив

2022-11-02 12:39 UTC, AegisVP commented on node/contactAPI.js
> +    return failure([]);
зробив

2022-11-02 12:41 UTC, AegisVP commented on node/contactAPI.js
> +  if (contacts.length <= 0) await listContacts();
Це задля економії читання файла. Зараз це не принципово, але якщо маштабувати сервер (на реальних проектах), про це варто задумуватись... Поки придумав тільки так, не факт що правильно. Це легко прибрати

2022-11-02 12:42 UTC, AegisVP commented on node/routes/contactsRouter.js
> +router.patch('/:id', async (req, res) => {
Прибрати PATCH? Я для себе зробив два різних щоб логіка відрізнялась (оновити все і оновити лише одне поле)

2022-11-02 18:02 UTC, Eastvarga commented on node/routes/contactsRouter.js
> +router.patch('/:id', async (req, res) => {
Так не робиться - один ендпоїнт котрий або потребує всі поля для оновлення, або любе поле та любий набор полів. Два ендпоінти для однієї задачи (оновлення об'єкту) це просто не раціонально