refactored for mongoDB and mongoose
AegisVP/goit-node-REST-API-HW pull request #4
Opened 2022-11-20 13:06 UTC by AegisVP

2022-11-20 17:34 UTC, Eastvarga commented on .env
> +DB_HOST="mongodb+srv://nodejsapp:e6F5xnbD0SmELCzC@cluster0.aesnroa.mongodb.net/?retryWrites=true&w=majority"
Чому цей файл у репозіторії? Ви подарували свої креди спільноті?

2022-11-20 17:35 UTC, Eastvarga commented on controller/contactsController.js
> +const joiValidateName = Joi.string().alphanum().min(1);
для чого ця конструкція? У Joi є валідація по схемі, навіщо щось дивне вигадувати?

2022-11-20 17:37 UTC, Eastvarga commented on controller/contactsController.js
> +  return res.json(generateSuccessData(contacts));
Читайте уважно завдання, де там в тілі відповіді поле status? Чи розумієте Ви що таке статус код відповіді?

2022-11-20 17:38 UTC, Eastvarga commented on controller/contactsController.js
> +  let errMsg = [];
Дивна валідація. Зробіть мідлвар валідації та використовуйте його перед сервісом. Перегляньте ще раз матеріали по валідації

2022-11-20 17:40 UTC, Eastvarga commented on controller/contactsController.js
> +  if (joiValidateFavorite.validate(favorite, { presence: 'required' }).error) errMsg.push('favorite');
Чому favorite обов'язкове поле для апдейту? Цього немає у ТЗ. Воно повинно бути опціональним, бо за замовченням воно  false

2022-11-20 17:43 UTC, Eastvarga commented on routes/contactsRouter.js
> +contactsRouter.post('/', tryCatchWrapper(contactsController.createContact));
Ось тут треба вілідації мідлвар
contactsRouter.post('/', validateContact, tryCatchWrapper(contactsController.getContacts));

2022-11-20 17:43 UTC, Eastvarga requested changes
Є зауваження.

2022-11-20 17:47 UTC, AegisVP commented on .env
> +DB_HOST="mongodb+srv://nodejsapp:e6F5xnbD0SmELCzC@cluster0.aesnroa.mongodb.net/?retryWrites=true&w=majority"
.gitignore не спрацював. .env доданий там

2022-11-20 17:48 UTC, AegisVP commented on controller/contactsController.js
> +const joiValidateName = Joi.string().alphanum().min(1);
Щоб можна було окремо кожне поле валідувати та видати сповіщення які саме поля не пройшли валідацію. Я не придумав іншого варіанту

2022-11-20 18:08 UTC, AegisVP commented on controller/contactsController.js
> +  return res.json(generateSuccessData(contacts));
це виправив

2022-11-20 18:10 UTC, AegisVP commented on controller/contactsController.js
> +  if (joiValidateFavorite.validate(favorite, { presence: 'required' }).error) errMsg.push('favorite');
Якщо його нема в body, воно стає false (і проходить валідацію без проблем). Якщо воно є в body, воно має пройти валідацію. Тут немає різниці взагалі чи воно помічене як обов'язкове.

2022-11-20 18:12 UTC, AegisVP commented on controller/contactsController.js
> +  if (joiValidateFavorite.validate(favorite, { presence: 'required' }).error) errMsg.push('favorite');
прибрав цю строку

2022-11-20 19:08 UTC, AegisVP commented on .env
> +DB_HOST="mongodb+srv://nodejsapp:e6F5xnbD0SmELCzC@cluster0.aesnroa.mongodb.net/?retryWrites=true&w=majority"
Пофіксив

2022-11-21 19:29 UTC, AegisVP commented on controller/contactsController.js
> +const joiValidateName = Joi.string().alphanum().min(1);
Прибрав, зробив валидацію через middleware

2022-11-21 21:36 UTC, AegisVP commented on controller/contactsController.js
> +  let errMsg = [];
Пофіксив

2022-11-21 21:36 UTC, AegisVP commented on routes/contactsRouter.js
> +contactsRouter.post('/', tryCatchWrapper(contactsController.createContact));
Пофіксив

2022-11-21 22:17 UTC, AegisVP commented
Всі зауваження прийняв до уваги та виправив

2022-11-22 06:44 UTC, Eastvarga commented on controller/contactsController.js
> +  if (joiValidateFavorite.validate(favorite, { presence: 'required' }).error) errMsg.push('favorite');
Якщо воно вказане у валідації як обов'язкове, то його відсутність поверне помилку у запиті!

2022-11-22 06:53 UTC, Eastvarga commented on schemas/contactJoiSchemas.js
> +  favorite: Joi.boolean(),
е метод optional() для необов'язкових полей

2022-11-22 06:54 UTC, Eastvarga approved these changes

2022-11-22 06:54 UTC, merged

2022-11-22 13:58 UTC, AegisVP commented on schemas/contactJoiSchemas.js
> +  favorite: Joi.boolean(),
Зрозумів, додам. Дякую